spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/loom?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
     ddl-auto: validate
    generate-ddl: false

  freemarker:
    expose-request-attributes: true

  mail:
   host: smtp.yandex.ru
   username: trofimenkomg@yandex.ru
   password: Exeption
   port: 465
   protocol: smtps

mail:
  debug: true

upload:
  path: "D:\\4"

recaptcha:
  secret: 6LfkuukUAAAAAOI_Y4j6cSZbI49HCLB11UC-CcHV
