spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loom?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
     ddl-auto: none
    generate-ddl: true
